name: Build to release

on:
  push:
    tags:
    - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build bot
      run: cargo build --release
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./target/release/bot
        token: ${{ secrets.GITHUB_TOKEN }}
